### ISSUE TITLE
publish as NPM and Bower package

### ISSUE THREAD

**Issue by theofidry** [GianlucaGuarini/Vague.js#15]
It would be really nice!

**Comment by GianlucaGuarini** [comment]
First you should not publish on npm a module developed and maintained by someone else and second Vague.js is already registered on bower

**Comment by theofidry** [comment]
Yeah I apologize I did it in haste and shouldn't.

Still, a Bower package is not an npm one. When you already use Composer and npm, it's really a pain to add Bower for only one package.

Moreover, you already have a package.json it's really just a matter of seconds...
