### ISSUE TITLE
IE10 issue

### ISSUE THREAD

**Issue by fefno** [GianlucaGuarini/Vague.js#23]
Why it doesn't work for IE10+?

**Comment by GianlucaGuarini** [comment]
please check http://caniuse.com/#search=filter

**Comment by fefno** [comment]
My question is why it doesn't work just for IE10+. It's work on IE9.

**Comment by eidia313** [comment]
I agree with @fefno . It would be a great plugin if it had included support for IE10+ browser.

**Comment by GianlucaGuarini** [comment]
I am sorry guys it is simply not possible on IE10+, neither the [css filters polyfill](https://github.com/Schepp/CSS-Filters-Polyfill) can solve this issue. I am closing this issue because ie sucks and we can't  anything
